name: test

on: [push, workflow_dispatch]

jobs:
  test-everywhere:
    name: Test Action on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]
        version: ["2017", "2019", "2022"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Run the action
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlclient, sqlpackage
          version: ${{ matrix.version }}
          sa-password: c0MplicatedP@ssword
          show-log: true
          collation: Latin1_General_BIN

      # - name: Run sqlcmd
      #   run: sqlcmd -C -S localhost -U sa -P c0MplicatedP@ssword -d tempdb -Q "SELECT @@version;"

      - name: Run sqlcmd with retry
        run: |
          for i in {1..3}; do
            echo "Attempt #$i..."
            if sqlcmd -C -S localhost -U sa -P c0MplicatedP@ssword -d tempdb -Q "SELECT @@version;"; then
              echo "sqlcmd succeeded on attempt #$i"
              break
            elif [ $i -lt 3 ]; then
              echo "sqlcmd failed. Retrying in 5 seconds..."
              sleep 5
            else
              echo "sqlcmd failed after 3 attempts."
              exit 1
            fi
          done
